version: "2.1"

services:
  cli:
    environment:
      - XDEBUG_ENABLED=0  # Disable Xdebug unless you need it
  db:
    image: mysql:8.0
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=default
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - db_data:/var/lib/mysql
