version: "2.1"

services:
  cli:
    environment:
      # Pass additional variables (used in custom commands, e.g. init-site) from host to cli
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - WP_ADMIN_USER
      - WP_ADMIN_PASS
      - WP_ADMIN_EMAIL
    volumes:
      - ${PROJECT_ROOT}:/var/www
    # Removed custom command to avoid issues with container initialization

# Add Adminer service
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080" # Adjust the first port number if you have another service using 8080
    environment:
      # Optional: Set some Adminer options
      ADMINER_DEFAULT_SERVER: db # This refers to your database service name
